[
	{
		city_mpg: 150,
		class: "midsize car",
		combination_mpg: 136,
		drive: "fwd",
		fuel_type: "electricity",
		highway_mpg: 122,
		make: "hyundai",
		model: "ioniq electric",
		transmission: "a",
		year: 2019,
	},
][
	({
		city_mpg: 15,
		class: "standard pickup truck",
		combination_mpg: 17,
		cylinders: 8,
		displacement: 4.6,
		drive: "rwd",
		fuel_type: "gas",
		highway_mpg: 19,
		make: "toyota",
		model: "tundra 2wd",
		transmission: "a",
		year: 2015,
	},
	{
		city_mpg: 13,
		class: "standard pickup truck",
		combination_mpg: 15,
		cylinders: 8,
		displacement: 5.7,
		drive: "rwd",
		fuel_type: "gas",
		highway_mpg: 18,
		make: "toyota",
		model: "tundra 2wd",
		transmission: "a",
		year: 2015,
	},
	{
		city_mpg: 14,
		class: "standard pickup truck",
		combination_mpg: 16,
		cylinders: 8,
		displacement: 4.6,
		drive: "4wd",
		fuel_type: "gas",
		highway_mpg: 18,
		make: "toyota",
		model: "tundra 4wd",
		transmission: "a",
		year: 2015,
	},
	{
		city_mpg: 13,
		class: "standard pickup truck",
		combination_mpg: 15,
		cylinders: 8,
		displacement: 5.7,
		drive: "4wd",
		fuel_type: "gas",
		highway_mpg: 17,
		make: "toyota",
		model: "tundra 4wd ffv",
		transmission: "a",
		year: 2015,
	},
	{
		city_mpg: 13,
		class: "standard pickup truck",
		combination_mpg: 15,
		cylinders: 8,
		displacement: 5.7,
		drive: "4wd",
		fuel_type: "gas",
		highway_mpg: 17,
		make: "toyota",
		model: "tundra 4wd",
		transmission: "a",
		year: 2015,
	})
][
	({
		city_mpg: 25,
		class: "compact car",
		combination_mpg: 28,
		cylinders: 4,
		displacement: 1.8,
		drive: "fwd",
		fuel_type: "gas",
		highway_mpg: 34,
		make: "toyota",
		model: "corolla",
		transmission: "a",
		year: 2004,
	},
	{
		city_mpg: 28,
		class: "compact car",
		combination_mpg: 31,
		cylinders: 4,
		displacement: 1.8,
		drive: "fwd",
		fuel_type: "gas",
		highway_mpg: 36,
		make: "toyota",
		model: "corolla",
		transmission: "m",
		year: 2004,
	})
][
	({
		city_mpg: 19,
		class: "small pickup truck",
		combination_mpg: 21,
		cylinders: 6,
		displacement: 3.5,
		drive: "rwd",
		fuel_type: "gas",
		highway_mpg: 24,
		make: "toyota",
		model: "tacoma 2wd",
		transmission: "a",
		year: 2020,
	},
	{
		city_mpg: 20,
		class: "small pickup truck",
		combination_mpg: 21,
		cylinders: 4,
		displacement: 2.7,
		drive: "rwd",
		fuel_type: "gas",
		highway_mpg: 23,
		make: "toyota",
		model: "tacoma 2wd",
		transmission: "a",
		year: 2020,
	},
	{
		city_mpg: 18,
		class: "small pickup truck",
		combination_mpg: 20,
		cylinders: 6,
		displacement: 3.5,
		drive: "4wd",
		fuel_type: "gas",
		highway_mpg: 22,
		make: "toyota",
		model: "tacoma 4wd",
		transmission: "a",
		year: 2020,
	},
	{
		city_mpg: 17,
		class: "small pickup truck",
		combination_mpg: 18,
		cylinders: 6,
		displacement: 3.5,
		drive: "4wd",
		fuel_type: "gas",
		highway_mpg: 21,
		make: "toyota",
		model: "tacoma 4wd",
		transmission: "m",
		year: 2020,
	},
	{
		city_mpg: 19,
		class: "small pickup truck",
		combination_mpg: 20,
		cylinders: 4,
		displacement: 2.7,
		drive: "4wd",
		fuel_type: "gas",
		highway_mpg: 22,
		make: "toyota",
		model: "tacoma 4wd",
		transmission: "a",
		year: 2020,
	},
	{
		city_mpg: 17,
		class: "small pickup truck",
		combination_mpg: 18,
		cylinders: 6,
		displacement: 3.5,
		drive: "4wd",
		fuel_type: "gas",
		highway_mpg: 20,
		make: "toyota",
		model: "tacoma 4wd d-cab mt trd-orp/pro",
		transmission: "m",
		year: 2020,
	})
];
